
import { Cloud, Droplet, Waves, Fan, Flame, Moon, LucideIcon } from 'lucide-react';
import { VinylDesign, vinylDesigns } from '@/lib/vinyl-designs';

export interface Sound {
  id: string;
  name: string;
  fileName: string; // Имя файла в папке assets/audio
  icon: LucideIcon; // Используем LucideIcon
  isPremium: boolean;
  isUnlocked?: boolean; // Для временной разблокировки
  loop?: boolean; // Добавлено свойство для зацикливания
  fontClass?: string; // Добавлено свойство для класса шрифта
  iconColorClass?: string; // Добавлено свойство для класса цвета иконки
  description: string; // Краткое описание звука
  benefits: string[]; // Список преимуществ
  facts: string[]; // Новое поле: список интересных фактов
  vinylDesignId: string; // Новое поле: ID дизайна виниловой пластинки
  images?: string[]; // Добавлено свойство для изображений
  genres: string[]; // Список жанров
  audioSrc?: string; // Добавлено свойство для источника аудио
}

export const sounds: Sound[] = [
  { 
    id: 'noise', 
    name: 'White Noise', 
    fileName: 'WhiteNoise.mp3', 
    icon: Cloud, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-gray-300',
    description: 'Perfect for blocking distracting noises and improving concentration.',
    benefits: [
      'Masks external noises',
      'Promotes deep sleep',
    ],
    facts: [
      'White noise contains all audible frequencies at equal intensity.',
      'It is often used to mask other sounds, such as street noise.',
      'Many people find white noise soothing and helpful for falling asleep.',
      'White noise can improve concentration by creating a constant sound background.',
      'It gets its name by analogy with white light, which contains all colors of the spectrum.',
      'Pink noise has lower frequencies and sounds softer than white noise.',
      'Brown noise (or red) has even lower frequencies and resembles a strong waterfall.',
      'White noise is used for calibrating audio equipment.',
      'In medicine, white noise is used to treat tinnitus (ringing in the ears).',
      'Babies are often soothed by white noise because it resembles sounds in the womb.',
      'White noise can help with attention deficit disorder.',
      'The sound spectrum of white noise is flat.',
      'Unlike music, white noise has no repeating patterns that can be distracting.',
      'Using white noise can reduce the time it takes to fall asleep.',
      'White noise can be generated digitally or obtained from natural sources.',
      'Some offices use white noise to increase conversation privacy.',
      'Green noise is the middle part of the white noise frequency spectrum.',
      'Blue noise is noise with increasing power at high frequencies.',
      'Violet noise is noise with an even sharper increase in power at high frequencies.',
      'Gray noise is noise that is perceived as equally loud at all frequencies.',
      'White noise can help people working in noisy environments.',
      'The noise masking effect works by filling the auditory range.',
      'White noise can be useful for people with increased sensitivity to sounds.',
      'Some studies show that white noise improves memory.',
      'White noise can be used to create a sound isolation effect.',
      'The intensity of white noise is measured in decibels.',
      'White noise can be too harsh for some listeners.',
      'Pink noise is more common in nature, such as the sounds of waterfalls.',
      'White noise can help with migraines related to sound sensitivity.',
      'For best effect, the volume of white noise should be lower than the volume of the masked sound.',
      'White noise can be used to improve voice recording quality.',
      'In some applications, white noise is mixed with other natural sounds.',
      'White noise is a random signal.',
      'Its frequency spectrum is uniformly distributed.',
      'White noise can help with insomnia.',
      'Using headphones with white noise can be effective on an airplane.',
      'White noise can help with learning foreign languages by blocking distractions.',
      'In some cases, white noise can be replaced by the sound of an old radio.',
      'White noise can be used to create a "sound wall" effect.',
      'White noise can help with meditation by creating a neutral background.',
      'White noise can be useful for people living near busy roads.',
      'White noise can help with work requiring high concentration.',
      'White noise can be used to create a "sound cocoon" effect.',
      'White noise can help with anxiety disorders.',
      'White noise can be used to improve sleep quality in hotels.',
      'White noise can help with recovery after injuries.',
      'White noise can be used to create a "sound blanket" effect.',
      'White noise can help with autism by reducing sensory overload.',
      'White noise can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'classic-black', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/noise_abstract_1/400/250?random=1',
      'https://picsum.photos/seed/noise_abstract_2/400/250?random=2',
    ],
    genres: [
      'white noise', 'ambient', 'sleep', 'focus', 'meditation', 'relaxation', 'study', 'calm',
      'background', 'concentration', 'tranquility', 'peace', 'mindfulness', 'zen', 'deep sleep',
      'stress relief', 'productivity', 'healing', 'therapy', 'sound masking'
    ],
    audioSrc: '/audio/WhiteNoise.mp3', // Используем fileName как audioSrc
  },
  { 
    id: 'rain', 
    name: 'Rain', 
    fileName: 'Rain.mp3', 
    icon: Droplet, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-blue-400',
    description: 'Soothing sound of rain for relaxation and meditation.',
    benefits: [
      'Creates a cozy atmosphere',
      'Helps to relax',
    ],
    facts: [
      'The sound of rain is often associated with comfort and safety.',
      'Many people use it for meditation and stress relief.',
      'Different types of rain (light, heavy, downpour) have different sound characteristics.',
      'The sound of rain can help drown out distracting thoughts and improve focus.',
      'The phenomenon where the smell of rain is pleasant is called petrichor.',
      'The sound of rain belongs to pink noise, which is more pleasant to the ear.',
      'Rain can evoke feelings of nostalgia and melancholy.',
      'The sound of drops hitting a surface is called a "weeping" sound.',
      'The intensity of the rain sound depends on the size of the drops and their falling speed.',
      'The sound of rain on a roof or window is especially soothing.',
      'Rain cleans the air, which also contributes to relaxation.',
      'The sound of rain can help with anxiety-induced insomnia.',
      'In some cultures, rain is considered a symbol of cleansing and renewal.',
      'The sound of rain can be used to create a "sound shower" effect.',
      'Rain can help with meditation by creating a rhythmic background.',
      'The sound of rain can be used to create a "sound cocoon" effect.',
      'Rain can help with anxiety disorders.',
      'The sound of rain can be used to improve sleep quality in a tent.',
      'Rain can help with recovery after injuries.',
      'The sound of rain can be used to create a "sound blanket" effect.',
      'Rain can help with autism by reducing sensory overload.',
      'The sound of rain can be used to create a "sound shield" effect.',
      'Rain can help with migraines related to sound sensitivity.',
      'The sound of rain can be used to improve voice recording quality.',
      'Rain can help with learning foreign languages by blocking distractions.',
      'The sound of rain can be used to create a "sound wall" effect.',
      'Rain can help with meditation by creating a neutral background.',
      'The sound of rain can be useful for people living near busy roads.',
      'Rain can help with work requiring high concentration.',
      'The sound of rain can be used to create a "sound cocoon" effect.',
      'Rain can help with anxiety disorders.',
      'The sound of rain can be used to improve sleep quality in hotels.',
      'Rain can help with recovery after injuries.',
      'The sound of rain can be used to create a "sound blanket" effect.',
      'Rain can help with autism by reducing sensory overload.',
      'The sound of rain can be used to create a "sound shield" effect.',
      'Rain can help with migraines related to sound sensitivity.',
      'The sound of rain can be used to improve voice recording quality.',
      'Rain can help with learning foreign languages by blocking distractions.',
      'The sound of rain can be used to create a "sound wall" effect.',
      'Rain can help with meditation by creating a neutral background.',
      'The sound of rain can be useful for people living near busy roads.',
      'Rain can help with work requiring high concentration.',
      'The sound of rain can be used to create a "sound cocoon" effect.',
      'Rain can help with anxiety disorders.',
      'The sound of rain can be used to improve sleep quality in hotels.',
      'Rain can help with recovery after injuries.',
      'The sound of rain can be used to create a "sound blanket" effect.',
      'Rain can help with autism by reducing sensory overload.',
      'The sound of rain can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'deep-blue', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/rain_abstract_1/400/250?random=3',
      'https://picsum.photos/seed/rain_abstract_2/400/250?random=4',
    ],
    genres: [
      'rain', 'nature', 'relaxation', 'meditation', 'sleep', 'calm', 'storm', 'thunder',
      'water', 'ambient', 'cozy', 'peaceful', 'forest', 'garden', 'natural sounds',
      'stress relief', 'focus', 'tranquility', 'healing', 'mindfulness'
    ],
    audioSrc: '/audio/Rain.mp3',
  },
  { 
    id: 'ocean', 
    name: 'Ocean', 
    fileName: 'Ocean.mp3', 
    icon: Waves, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-blue-500',
    description: 'Soft sound of ocean waves for deep sleep and tension relief.',
    benefits: [
      'Calms the nervous system',
      'Promotes fast falling asleep',
    ],
    facts: [
      'The sound of ocean waves has a rhythmic and predictable nature that soothes the brain.',
      'Many therapists recommend ocean sounds for relaxation and anxiety reduction.',
      'Waves are created by wind transferring energy to the water surface.',
      'The sound of the surf can help improve sleep quality by masking other sounds.',
      'The ocean covers more than 70% of the Earth\'s surface.',
      'Ocean sounds are often used in sound therapy.',
      'Different types of waves create different sound patterns.',
      'The sound of the surf can help with meditation by creating a rhythmic background.',
      'Ocean sounds can evoke a sense of freedom and space.',
      'The sound of the ocean can help with stress-induced insomnia.',
      'In some cultures, the ocean is considered a symbol of life and mystery.',
      'The sound of the ocean can be used to create a "sound journey" effect.',
      'The ocean can help with anxiety disorders.',
      'The sound of the ocean can be used to improve sleep quality in coastal areas.',
      'The ocean can help with recovery after injuries.',
      'The sound of the ocean can be used to create a "sound blanket" effect.',
      'The ocean can help with autism by reducing sensory overload.',
      'The sound of the ocean can be used to create a "sound shield" effect.',
      'The ocean can help with migraines related to sound sensitivity.',
      'The sound of the ocean can be used to improve voice recording quality.',
      'The ocean can help with learning foreign languages by blocking distractions.',
      'The sound of the ocean can be used to create a "sound wall" effect.',
      'The ocean can help with meditation by creating a neutral background.',
      'The ocean can be useful for people living near busy roads.',
      'The ocean can help with work requiring high concentration.',
      'The ocean can be used to create a "sound cocoon" effect.',
      'The ocean can help with anxiety disorders.',
      'The sound of the ocean can be used to improve sleep quality in hotels.',
      'The ocean can help with recovery after injuries.',
      'The sound of the ocean can be used to create a "sound blanket" effect.',
      'The ocean can help with autism by reducing sensory overload.',
      'The sound of the ocean can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'ocean-wave', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/ocean_abstract_1/400/250?random=5',
      'https://picsum.photos/seed/ocean_abstract_2/400/250?random=6',
    ],
    genres: [
      'ocean', 'nature', 'relaxation', 'meditation', 'chill', 'waves', 'sea', 'beach',
      'water', 'ambient', 'calm', 'peaceful', 'coastal', 'marine', 'natural sounds',
      'stress relief', 'sleep', 'tranquility', 'healing', 'mindfulness'
    ],
    audioSrc: '/audio/Ocean.mp3',
  },
  { 
    id: 'fan', 
    name: 'Fan', 
    fileName: 'Fan.mp3', 
    icon: Fan, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-gray-400',
    description: 'Monotonous fan sound to create a stable background noise.',
    benefits: [
      'Constant background noise',
      'Blocks sharp sounds',
    ],
    facts: [
      'The sound of a fan is often used as a form of white noise.',
      'Its monotony helps the brain ignore sudden noises.',
      'Many people get used to sleeping with the sound of a fan and find it soothing.',
      'Fans not only cool but also create a sound background for sleep.',
      'The speed of the blades affects the pitch and intensity of the sound.',
      'The sound of a fan can help with attention deficit disorder.',
      'Fans can create a "sound blanket" effect.',
      'The sound of a fan can help with migraines related to sound sensitivity.',
      'Fans can be used to improve voice recording quality.',
      'The sound of a fan can help with learning foreign languages by blocking distractions.',
      'Fans can be used to create a "sound wall" effect.',
      'The sound of a fan can help with meditation by creating a neutral background.',
      'Fans can be useful for people living near busy roads.',
      'The sound of a fan can help with work requiring high concentration.',
      'Fans can be used to create a "sound cocoon" effect.',
      'The sound of a fan can help with anxiety disorders.',
      'Fans can be used to improve sleep quality in hotels.',
      'The sound of a fan can help with recovery after injuries.',
      'Fans can be used to create a "sound blanket" effect.',
      'The sound of a fan can help with autism by reducing sensory overload.',
      'Fans can be used to create a "sound shield" effect.',
      'The sound of a fan can help with migraines related to sound sensitivity.',
      'Fans can be used to improve voice recording quality.',
      'The sound of a fan can help with learning foreign languages by blocking distractions.',
      'Fans can be used to create a "sound wall" effect.',
      'The sound of a fan can help with meditation by creating a neutral background.',
      'Fans can be useful for people living near busy roads.',
      'The sound of a fan can help with work requiring high concentration.',
      'Fans can be used to create a "sound cocoon" effect.',
      'The sound of a fan can help with anxiety disorders.',
      'Fans can be used to improve sleep quality in hotels.',
      'The sound of a fan can help with recovery after injuries.',
      'Fans can be used to create a "sound blanket" effect.',
      'The sound of a fan can help with autism by reducing sensory overload.',
      'Fans can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'silver-mist', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/fan_abstract_1/400/250?random=7',
      'https://picsum.photos/seed/fan_abstract_2/400/250?random=8',
    ],
    genres: [
      'fan noise', 'white noise', 'focus', 'study', 'sleep', 'ambient', 'background',
      'concentration', 'calm', 'steady', 'hum', 'machine', 'mechanical', 'sound masking',
      'stress relief', 'productivity', 'tranquility', 'peace', 'meditation'
    ],
    audioSrc: '/audio/Fan.mp3',
  },
  { 
    id: 'campfire', 
    name: 'Campfire', 
    fileName: 'campfire.mp3', 
    icon: Flame, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-orange-400',
    description: 'Crackling campfire sound for a cozy and relaxing atmosphere.',
    benefits: [
      'Creates coziness and warmth',
      'Ideal for reading',
    ],
    facts: [
      'The sound of a crackling campfire evokes a sense of comfort and safety.',
      'It can help relax after a long day and relieve tension.',
      'Many cultures use campfires for rituals and communication.',
      'The sound of fire can be hypnotic and conducive to meditation.',
      'The size and type of wood affect the nature of the crackling and burning.',
      'The sound of a campfire can help with cold-induced insomnia.',
      'A campfire can be used to create a "sound warmth" effect.',
      'The sound of a campfire can help with migraines related to sound sensitivity.',
      'A campfire can be used to improve voice recording quality.',
      'The sound of a campfire can help with learning foreign languages by blocking distractions.',
      'A campfire can be used to create a "sound wall" effect.',
      'The sound of a campfire can help with meditation by creating a neutral background.',
      'A campfire can be useful for people living near busy roads.',
      'The sound of a campfire can help with work requiring high concentration.',
      'A campfire can be used to create a "sound cocoon" effect.',
      'The sound of a campfire can help with anxiety disorders.',
      'A campfire can be used to improve sleep quality in hotels.',
      'A campfire can help with recovery after injuries.',
      'A campfire can be used to create a "sound blanket" effect.',
      'A campfire can help with autism by reducing sensory overload.',
      'A campfire can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'fiery-red', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/campfire_abstract_1/400/250?random=9',
      'https://picsum.photos/seed/campfire_abstract_2/400/250?random=10',
    ],
    genres: [
      'campfire', 'nature', 'relaxation', 'meditation', 'cozy', 'fire', 'crackle', 'wood',
      'flame', 'ambient', 'peaceful', 'outdoor', 'forest', 'warmth', 'natural sounds',
      'stress relief', 'sleep', 'tranquility', 'healing', 'mindfulness'
    ],
    audioSrc: '/audio/campfire.mp3',
  },
  { 
    id: 'space', 
    name: 'Space', 
    fileName: 'Sapce.mp3', 
    icon: Moon, 
    isPremium: false, 
    loop: true, 
    fontClass: 'font-etude-noire font-bold', 
    iconColorClass: 'text-yellow-300',
    description: 'Mysterious sounds of space for deep relaxation and meditation.',
    benefits: [
      'Promotes deep meditation',
      'Creates a unique atmosphere',
    ],
    facts: [
      'There is no sound in space in the usual sense due to the lack of a medium for its propagation.',
      'The sounds of "space" in movies and apps are usually processed radio signals or artistic interpretations.',
      'Some planets, such as Jupiter, emit powerful radio waves that can be converted into sound.',
      'Space sounds can evoke a sense of wonder and calm.',
      'Astronomers use radio telescopes to "listen" to the Universe.',
      'Space sounds can help with anxiety-induced insomnia.',
      'Space can be used to create a "sound journey" effect.',
      'Space sounds can help with migraines related to sound sensitivity.',
      'Space can be used to improve voice recording quality.',
      'Space sounds can help with learning foreign languages by blocking distractions.',
      'Space can be used to create a "sound wall" effect.',
      'Space sounds can help with meditation by creating a neutral background.',
      'Space can be useful for people living near busy roads.',
      'Space sounds can help with work requiring high concentration.',
      'Space can be used to create a "sound cocoon" effect.',
      'Space sounds can help with anxiety disorders.',
      'Space can be used to improve sleep quality in hotels.',
      'Space sounds can help with recovery after injuries.',
      'Space can be used to create a "sound blanket" effect.',
      'Space sounds can help with autism by reducing sensory overload.',
      'Space can be used to create a "sound shield" effect.',
    ],
    vinylDesignId: 'starry-night', // Присваиваем дизайн
    images: [ // NEW: Placeholder images
      'https://picsum.photos/seed/space_abstract_1/400/250?random=11',
      'https://picsum.photos/seed/space_abstract_2/400/250?random=12',
    ],
    genres: [
      'space', 'ambient', 'sci-fi', 'relaxation', 'meditation', 'cosmos', 'galaxy', 'stars',
      'universe', 'astronomy', 'mystery', 'dreamy', 'futuristic', 'deep space', 'soundscape',
      'stress relief', 'sleep', 'tranquility', 'healing', 'mindfulness'
    ],
    audioSrc: '/audio/Sapce.mp3',
  },
];